### ISSUE TITLE
Safely uninstall KoboOmnivoreConverter from Kobo device

### ISSUE THREAD

**Issue by Akasiek** [Podginator/KoboOmnivoreConverter#11]
Hi! Since Omnivore is being discontinued, can you write a simple guide to uninstall KoboOmnivoreConverter from Kobo and undo all the changes so that Pocket can be used again?

**Comment by Podginator** [comment]
Hi Akasiek. 

I'll update the guide. 

In the meantime you can do the following - 

Telnet into the device
`rm -rf /usr/local/Kobo/imageformats/libpocket.so`

Then remove the configuration (Api key)

**Comment by Akasiek** [comment]
Thanks! And also thank you for developing and supporting this app
