### ISSUE TITLE
Router based redirect

### ISSUE THREAD

**Issue by sefsh** [Podginator/KoboOmnivoreConverter#2]
If this is run within a local network, is it possible to redirect Pocket calls on the router instead of having to modify the Kobo host file to do so?

**Comment by Podginator** [comment]
Yes, I think that should work absolutely fine.

**Comment by Podginator** [comment]
I haven't actually tested it with redirection from the router, but I imagine that yes it would still need to go via http rather than https just for the SSL cert. I
